# Data Cleaning and Validation

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Data.csv")

In [ ]:
df.shape
print(f"No. of Rows : {df.shape[0] }")
print(f"No. of Columns : {df.shape[1] }")

No. of Rows : 31779
No. of Columns : 27

In [ ]:
df.columns

Index(['date', 'year', 'month', 'day', 'dayofweek', 'is_weekend', 'season',
       'city', 'region', 'latitude', 'longitude', 'elevation', 'tmin', 'tmax',
       'tavg', 'prcp', 'wspd', 'humidity', 'pressure', 'dew_point',
       'cloud_cover', 'visibility', 'temp_range', 'is_hot_day', 'is_cold_day',
       'rainfall_intensity', 'wind_category'],
      dtype='str')

In [ ]:
df.dtypes

date                      str
year                    int64
month                   int64
day                     int64
dayofweek               int64
is_weekend              int64
season                    str
city                      str
region                    str
latitude              float64
longitude             float64
elevation               int64
tmin                  float64
tmax                  float64
tavg                  float64
prcp                  float64
wspd                  float64
humidity                int64
pressure              float64
dew_point             float64
cloud_cover             int64
visibility            float64
temp_range            float64
is_hot_day              int64
is_cold_day             int64
rainfall_intensity        str
wind_category             str
dtype: object

In [ ]:
df.head()

,date,year,month,day,dayofweek,is_weekend,season,city,region,latitude,...,humidity,pressure,dew_point,cloud_cover,visibility,temp_range,is_hot_day,is_cold_day,rainfall_intensity,wind_category
0,1/1/2000,2000,1,1,5,1,Winter,Islamabad,Punjab,33.6844,...,76,1018.9,4.8,0,NaN,14.1,0,0,none,windy
1,1/2/2000,2000,1,2,6,1,Winter,Islamabad,Punjab,33.6844,...,77,1018.6,4.8,0,NaN,14.5,0,0,none,windy
2,1/3/2000,2000,1,3,0,0,Winter,Islamabad,Punjab,33.6844,...,76,1016.8,5.0,0,NaN,14.6,0,0,none,windy
3,1/4/2000,2000,1,4,1,0,Winter,Islamabad,Punjab,33.6844,...,75,1016.2,4.8,0,NaN,14.2,0,0,none,windy
4,1/5/2000,2000,1,5,2,0,Winter,Islamabad,Punjab,33.6844,...,77,1017.5,5.3,0,NaN,14.3,0,0,none,windy

In [ ]:
df.isna().sum()

date                      0
year                      0
month                     0
day                       0
dayofweek                 0
is_weekend                0
season                    0
city                      0
region                    0
latitude                  0
longitude                 0
elevation                 0
tmin                      0
tmax                      0
tavg                      0
prcp                      0
wspd                      0
humidity                  0
pressure                  0
dew_point                 0
cloud_cover               0
visibility            31779
temp_range                0
is_hot_day                0
is_cold_day               0
rainfall_intensity        0
wind_category             0
dtype: int64

In [ ]:
df = df.drop(columns='visibility') # all values of Visibilty are missing so it is droped.

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,year,month,day,dayofweek,is_weekend,latitude,longitude,elevation,tmin,tmax,tavg,prcp,wspd,humidity,pressure,dew_point,cloud_cover,temp_range,is_hot_day,is_cold_day
count,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000,31779.000000
mean,2011.103370,6.522609,15.730577,3.000063,0.285818,31.759637,71.239903,651.656817,15.186488,25.787577,20.355449,1.717801,12.902307,58.138614,1010.829195,10.129120,32.852104,10.601089,0.009755,0.067340
std,7.176794,3.448845,8.800627,2.000267,0.451810,3.653211,2.976196,590.625245,9.613917,9.814480,9.573290,5.971060,7.857757,18.456379,8.481143,10.263861,30.246910,3.787311,0.098285,0.250614
min,2000.000000,1.000000,1.000000,0.000000,0.000000,24.860700,66.975000,8.000000,-21.300000,-12.900000,-15.600000,0.000000,0.800000,6.000000,989.700000,-28.700000,0.000000,0.700000,0.000000,0.000000
25%,2005.000000,4.000000,8.000000,1.000000,0.000000,30.179800,67.001100,217.000000,8.100000,19.700000,13.500000,0.000000,7.900000,45.000000,1004.000000,3.700000,5.000000,7.800000,0.000000,0.000000
50%,2010.000000,7.000000,16.000000,3.000000,0.000000,33.684400,73.047900,540.000000,16.700000,28.500000,22.700000,0.000000,11.300000,61.000000,1011.400000,10.300000,25.000000,10.500000,0.000000,0.000000
75%,2017.000000,10.000000,23.000000,5.000000,1.000000,34.015100,73.047900,1500.000000,23.500000,32.800000,28.000000,0.500000,16.800000,73.000000,1016.800000,18.800000,55.000000,13.400000,0.000000,0.000000
max,2024.000000,12.000000,31.000000,6.000000,1.000000,35.922100,74.343600,1680.000000,32.600000,47.300000,39.200000,201.100000,50.600000,96.000000,1042.900000,27.500000,100.000000,22.500000,1.000000,1.000000

In [ ]:
df.dtypes

date                      str
year                    int64
month                   int64
day                     int64
dayofweek               int64
is_weekend              int64
season                    str
city                      str
region                    str
latitude              float64
longitude             float64
elevation               int64
tmin                  float64
tmax                  float64
tavg                  float64
prcp                  float64
wspd                  float64
humidity                int64
pressure              float64
dew_point             float64
cloud_cover             int64
temp_range            float64
is_hot_day              int64
is_cold_day             int64
rainfall_intensity        str
wind_category             str
dtype: object

In [ ]:
df = df.astype({
    "date" : "datetime64[ns]",
    "season": "category",
    "city": "category",
    "region": "category",
    "rainfall_intensity": "category",
    "wind_category": "category"
})

print(df.dtypes)

date                  datetime64[ns]
year                           int64
month                          int64
day                            int64
dayofweek                      int64
is_weekend                     int64
season                      category
city                        category
region                      category
latitude                     float64
longitude                    float64
elevation                      int64
tmin                         float64
tmax                         float64
tavg                         float64
prcp                         float64
wspd                         float64
humidity                       int64
pressure                     float64
dew_point                    float64
cloud_cover                    int64
temp_range                   float64
is_hot_day                     int64
is_cold_day                    int64
rainfall_intensity          category
wind_category               category
dtype: object

Saving Data:

In [ ]:
df.to_csv('CleanData.csv', index=False)

# Observations:
1. visibilty column has all missing rows so whole column was droped.
2. no other missing values.
3. no Duplicate Values.
4. Data types of some columns were changed to make data set suitable for training models on it.